name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge
        run: |
          forge --version
          forge build --sizes
          forge test -vvv
        id: build-test
        env:
          BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}

